version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "helius-webhook-stack"
s3_bucket = "helius-webhook-deployment-418295715028"
s3_prefix = "helius-webhook"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SnowflakePassword=RESU_WOLFRIA AirflowPassword=admin"
confirm_changeset = false
resolve_s3 = false
