AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Helius Webhook Handler with Lambda Layers

Parameters:
  SnowflakeAccount:
    Type: String
    Default: "your-account"
  
  SnowflakeUser:
    Type: String
    Default: "your-user"
  
  SnowflakePassword:
    Type: String
    NoEcho: true
  
  SnowflakeWarehouse:
    Type: String
    Default: "DEV_WH"
  
  SnowflakeDatabase:
    Type: String
    Default: "DEV"
  
  SnowflakeSchema:
    Type: String
    Default: "BRONZE"
  
  SnowflakeRole:
    Type: String
    Default: "AIRFLOW_ROLE"
  
  AirflowEndpoint:
    Type: String
    Default: "http://52.205.187.101:8080"
  
  AirflowUsername:
    Type: String
    Default: "admin"
  
  AirflowPassword:
    Type: String
    NoEcho: true

Resources:
  SnowflakeLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: snowflake-layer
      Description: Dependencies for Snowflake connectivity
      ContentUri: ./layers/snowflake_layer/
      CompatibleRuntimes:
        - python3.11
      RetentionPolicy: Retain

  UtilityLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: utility-layer
      Description: Utility dependencies like requests and boto3
      ContentUri: ./layers/utility_layer/
      CompatibleRuntimes:
        - python3.11
      RetentionPolicy: Retain

  HeliusWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda/
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Timeout: 30
      MemorySize: 256
      Layers:
        - !Ref SnowflakeLayer
        - !Ref UtilityLayer
      Environment:
        Variables:
          SNOWFLAKE_ACCOUNT: !Ref SnowflakeAccount
          SNOWFLAKE_USER: !Ref SnowflakeUser
          SNOWFLAKE_PASSWORD: !Ref SnowflakePassword
          SNOWFLAKE_WAREHOUSE: !Ref SnowflakeWarehouse
          SNOWFLAKE_DATABASE: !Ref SnowflakeDatabase
          SNOWFLAKE_SCHEMA: !Ref SnowflakeSchema
          SNOWFLAKE_ROLE: !Ref SnowflakeRole
          AIRFLOW_ENDPOINT: !Ref AirflowEndpoint
          AIRFLOW_USERNAME: !Ref AirflowUsername
          AIRFLOW_PASSWORD: !Ref AirflowPassword
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /webhook
            Method: post

Outputs:
  ApiUrl:
    Description: URL of the API endpoint
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook'
  FunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt HeliusWebhookFunction.Arn