AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Webhook Listener for Helius with Snowflake integration

Parameters:
  S3BucketNamePrefix:
    Type: String
    Description: Prefix for the S3 bucket name
    Default: helius-webhook
  SnowflakePassword:
    Type: String
    Description: Password for Snowflake connection
    NoEcho: true
  AirflowPassword:
    Type: String
    Description: Password for Airflow connection
    NoEcho: true

Resources:
  WebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./package/
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          S3_BUCKET: !Ref RawDataBucket
          SNOWFLAKE_ACCOUNT: dhpplkl-fxb50377
          SNOWFLAKE_USER: AIRFLOW_USER
          SNOWFLAKE_PASSWORD: !Ref SnowflakePassword
          SNOWFLAKE_WAREHOUSE: DEV_WH
          SNOWFLAKE_DATABASE: DEV
          SNOWFLAKE_SCHEMA: BRONZE
          SNOWFLAKE_ROLE: AIRFLOW_ROLE
          AIRFLOW_ENDPOINT: http://52.205.187.101:8080
          AIRFLOW_USERNAME: admin
          AIRFLOW_PASSWORD: !Ref AirflowPassword
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref RawDataBucket
      Events:
        WebhookAPI:
          Type: Api
          Properties:
            Path: /webhooks
            Method: post

  RawDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${S3BucketNamePrefix}-${AWS::AccountId}-${AWS::Region}"
 
Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhooks"
  
  S3BucketName:
    Description: "S3 Bucket for raw webhook data"
    Value: !Ref RawDataBucket
  
  WebhookFunctionArn:
    Description: "Lambda function ARN"
    Value: !GetAtt WebhookFunction.Arn